apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.5"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    jmxOptions:
      "-Xms": 8192m
      "-Xmx": 8192m
    listeners:
      external:
        tls: false
        type: nodeport
      plain: {}
      tls: {}
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    storage:
      class: local-path
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsUser: 0
    version: 2.5.0
  zookeeper:
    jmxOptions:
      "-Xms": 4096m
      "-Xmx": 4096m
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    storage:
      class: local-path
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsUser: 0
