apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-test-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /kafka
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.34.81
  volumeMode: Filesystem
  storageClassName: local-path
