apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-test-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: kafka-test-pv
