apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo-stunnel
  labels:
    app: zoo-stunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo-stunnel
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zoo-stunnel
    spec:
      containers:
        - name: zoo-stunnel
          image: harbor-b.alauda.cn/3rdparty/strimzi/cmak-ui:origin_master-b7-c0f0cbc.0
          command:
            - /opt/stunnel/stunnel_run.sh
          ports:
            - containerPort: 2181
              name: zoo
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: notice
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: my-cluster-zookeeper-client:2181 # todo
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - "2181"
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - "2181"
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /etc/cluster-operator-certs/
              name: cluster-operator-certs
            - mountPath: /etc/cluster-ca-certs/
              name: cluster-ca-certs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cluster-operator-certs
          secret:
            defaultMode: 288
            secretName: my-cluster-cluster-operator-certs # todo
        - name: cluster-ca-certs
          secret:
            defaultMode: 288
            secretName: my-cluster-cluster-ca-cert # todo

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoo-stunnel
  name: zoo-stunnel
spec:
  ports:
    - name: zoo
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: zoo-stunnel
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: zoo-stunnel
  name: zoo-stunnel
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: zoo-stunnel
      ports:
        - port: 2181
          protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-zookeeper # todo
  policyTypes:
    - Ingress